/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiketwebservice.ui;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author user
 */
public class Acara extends javax.swing.JFrame implements Runnable {

    public String usn;
    public String nama_acara = "";
    public String kategori = "";
    public String lokasi = "";
    public Date tanggal_acara = null;
    public String idAcr = "";
    public String kapasitas_awal = "";
    public String kapasitas_sisa = "";

    /**
     * Creates new form Acara
     */
    Socket s;
    Thread t;
    BufferedReader in;
    DataOutputStream out;

    public Acara() {
        try {
            initComponents();

            //TCP
            s = new Socket("localhost", 6002);
            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }
        } catch (IOException ex) {
            System.out.println("Error di constructor = " + ex);
        }
    }

    public static void main(String args[]) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new Acara().setVisible(true);
            }
        });
    }

    public void isiData() {
        txtNama.setText(usn);
    }

    public void tampil() {
        tampilDaftarAcara();
    }

    public void tampilDaftarAcara() {
        try {
            String chatClient;
            chatClient = "Lihat Daftar Acara";
            DataOutputStream out = new DataOutputStream(s.getOutputStream());
            out.writeBytes(chatClient + "\n");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        txtNama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAcara = new javax.swing.JTable();
        jButtonReserve = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setFont(new java.awt.Font("Verdana", 1, 34)); // NOI18N
        txtNama.setText("nama");
        jPanelMain.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        tableAcara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Acara", "Kategori", "Lokasi", "Tanggal", "Kapasitas Awal", "Kapasitas Sisa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAcara.setSelectionBackground(new java.awt.Color(107, 114, 61));
        tableAcara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAcaraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAcara);

        jPanelMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 860, 360));

        jButtonReserve.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButtonReserve.setText("RESERVE");
        jButtonReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReserveActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, -1, -1));

        buttonBack.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        buttonBack.setText("<");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanelMain.add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 15, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/images/bgAcara.png"))); // NOI18N
        jPanelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableAcaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAcaraMouseClicked
        JTable val = (JTable) evt.getSource();
        int row = val.getSelectedRow();// TODO add your handling code here:
        if (row != -1) { //jadi getSelectedRow() ini kalo misale gaada baris yang dipilih, dee bakal return -1, makae if row != -1
            idAcr = val.getValueAt(row, 0).toString();
            nama_acara = val.getValueAt(row, 1).toString();
            kategori = val.getValueAt(row, 2).toString();
            lokasi = val.getValueAt(row, 3).toString();
            tanggal_acara = Date.valueOf(val.getValueAt(row, 4).toString());
            kapasitas_awal = val.getValueAt(row, 5).toString();
            kapasitas_sisa = val.getValueAt(row, 6).toString();
        } else {
            idAcr = "";
            nama_acara = "";
            kategori = "";
            lokasi = "";
            tanggal_acara = null;
            kapasitas_awal = "";
            kapasitas_sisa = "";
        }
    }//GEN-LAST:event_tableAcaraMouseClicked

    private void jButtonReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReserveActionPerformed
        if (!nama_acara.isEmpty() && !kategori.isEmpty() && !lokasi.isEmpty() && tanggal_acara != null && !kapasitas_awal.isEmpty() && !kapasitas_sisa.isEmpty()) {
            DetailPesanAcara form = new DetailPesanAcara();
            System.out.println("Nama: " + nama_acara);
            form.nama_acara = nama_acara;
            form.kategori = kategori;
            form.lokasi = lokasi;
            form.tanggal_acara = tanggal_acara;
            form.usn = usn;
            form.idAcr = idAcr;
            form.tampil();
            form.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Harap memilih sebuah acara terlebih dahulu!");
        }
    }//GEN-LAST:event_jButtonReserveActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        WelcomePage form = new WelcomePage();
        form.setVisible(true);
        this.setVisible(false);
        form.usn = usn;
        form.isiData();
    }//GEN-LAST:event_buttonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void run() {
        while (true) {
            try {
                while (true) {
                    getMessage();
                }
            } catch (Exception e) {
            }
        }
    }

    public void getMessage() throws IOException {
        String chatServer;

        in = new BufferedReader(new InputStreamReader(s.getInputStream()));
        chatServer = in.readLine();

        String[] arrayDariServer = chatServer.split("-n");

        String status = arrayDariServer[0];

        if (status.equals("Daftar Acara")) {
            String textLong = arrayDariServer[1];
            String[] arrayDariTextLong = textLong.split("#");

            DefaultTableModel model = (DefaultTableModel) tableAcara.getModel();
            model.setRowCount(0);
            Object[] rowData = new Object[7];

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate tanggalHariIni = LocalDate.now();

            int i = 0;
            for (i = 0; i < arrayDariTextLong.length; i++) {

                String textAkhir = arrayDariTextLong[i];
                System.out.println(i);
                System.out.println(arrayDariTextLong.length);
                String[] arrayFix = textAkhir.split("-m");
                String idAcara = arrayFix[0];
                System.out.println(idAcara);
                String namaAcara = arrayFix[1];
                String kategoriAcara = arrayFix[2];
                String lokasiAcara = arrayFix[3];
                String tanggalAcara = arrayFix[4];
                int kapasitasAwal = Integer.parseInt(arrayFix[5]);
                int kapasitasSisa = Integer.parseInt(arrayFix[6]);

                LocalDate eventDate = LocalDate.parse(tanggalAcara, formatter);

                //cuma nampilin acara yang belum lewat / sebelum hari ini
                if (eventDate.isAfter(tanggalHariIni) || eventDate.equals(tanggalHariIni) && kapasitasSisa > 0 ) {
                    rowData[0] = idAcara;
                    rowData[1] = namaAcara;
                    rowData[2] = kategoriAcara;
                    rowData[3] = lokasiAcara;
                    rowData[4] = tanggalAcara;
                    rowData[5] = kapasitasAwal;
                    rowData[6] = kapasitasSisa;
                    model.addRow(rowData);
                }
            }
            while (i < arrayDariTextLong.length) {
                i++;
            }

            //sembunyiin kolom id
            TableColumnModel tcm = tableAcara.getColumnModel();
            tableAcara.getColumnModel().getColumn(0).setWidth(0);
            tableAcara.getColumnModel().getColumn(0).setMinWidth(0);
            tableAcara.getColumnModel().getColumn(0).setMaxWidth(0);

            //jadiin isi tabel center smua
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
            for (int j = 0; j < tableAcara.getColumnCount(); j++) {
                tableAcara.getColumnModel().getColumn(j).setCellRenderer(centerRenderer);
            }

            //tambahin sekat / grid antar kolom
            tableAcara.setShowGrid(true);
            tableAcara.setGridColor(Color.GRAY);
            tableAcara.setIntercellSpacing(new java.awt.Dimension(1, 1));

            //ganti font dan ukuran tulisan dalam table
            Font font = new Font("Nunito", Font.PLAIN, 15);
            tableAcara.setFont(font);
            tableAcara.setRowHeight(30); //ini tinggi per cell (sesuaiin sama font aja)

        } else if (status.equals("Gagal Daftar Acara")) {
            System.out.println("Tidak ada daftar acara");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton jButtonReserve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAcara;
    private javax.swing.JLabel txtNama;
    // End of variables declaration//GEN-END:variables
}
