/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiketwebservice.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.sql.Date;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ClaimTicketAcara extends javax.swing.JFrame implements Runnable {

    public String usn;
    public String nama_acara;
    public String kategori;
    public String lokasi;
    public Date tanggal_acara;
    public String idRacr;
    public String idAcara;

    Socket s;
    Thread t;
    BufferedReader in;
    DataOutputStream out;

    /**
     * Creates new form ClaimTicketAcara
     */
    public ClaimTicketAcara() {
        try {
            initComponents();

            //TCP
            s = new Socket("localhost", 6002);
            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }
        } catch (IOException ex) {
            System.out.println("Error di constructor = " + ex);
        }
    }

    public void tampil() {
        System.out.println("Masuk Claim");
        System.out.println(nama_acara);
        labelNamaAcr.setText(nama_acara);
        labelKat.setText(kategori);
        labelLokasi.setText(lokasi);
        labelNamaAkun.setText(usn);
        labelTgl.setText(tanggal_acara.toString());
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        labelNamaAkun = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelKat = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelLokasi = new javax.swing.JLabel();
        labelTgl = new javax.swing.JLabel();
        labelNamaAcr = new javax.swing.JLabel();
        jButtonClaim = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Nama Pemesan");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        labelNamaAkun.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNamaAkun.setText("namaPemesan");
        jPanel2.add(labelNamaAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText(":");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 19, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setText(":");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 19, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText(":");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 19, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText(":");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 19, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText(":");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 19, -1));

        labelKat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelKat.setText("kategori");
        jPanel2.add(labelKat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Lokasi Acara");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Tanggal Acara ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Kategori");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Nama Acara");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        labelLokasi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelLokasi.setText("lokasi");
        jPanel2.add(labelLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        labelTgl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTgl.setText("tanggal_acara");
        jPanel2.add(labelTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        labelNamaAcr.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNamaAcr.setText("nama_acara");
        jPanel2.add(labelNamaAcr, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jButtonClaim.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButtonClaim.setText("Claim Ticket");
        jButtonClaim.setToolTipText("");
        jButtonClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClaimActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 210, 40));

        buttonBack.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        buttonBack.setText("<");
        buttonBack.setToolTipText("");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel2.add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/images/bgKonfirmasiClaimTicketAcara.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClaimActionPerformed
        // TODO add your handling code here:
        try {
            String chatClient;
            chatClient = "Claim Ticket Acara-n" + usn + "-m" + idRacr + "-m" + idAcara;
            System.out.println(chatClient);
            DataOutputStream out = new DataOutputStream(s.getOutputStream());
            out.writeBytes(chatClient + "\n");
            getMessage();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonClaimActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        try {
            // TODO add your handling code here:
            DaftarAcaraPending form = new DaftarAcaraPending();
            form.setVisible(true);
            this.setVisible(false);
            form.usn = usn;
            form.isiData();
            form.tampil();
            form.getMessage();
        } catch (IOException ex) {
            Logger.getLogger(ClaimTicketAcara.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBackActionPerformed

    @Override
    public void run() {
        while (true) {
        }
    }

    public void getMessage() throws IOException {
        String chatServer;

        in = new BufferedReader(new InputStreamReader(s.getInputStream()));
        chatServer = in.readLine();
        System.out.println(chatServer);

        String[] arrayDariServer = chatServer.split("-n");
        String status = arrayDariServer[0];

        if (status.equals("Berhasil Claim Ticket Acara")) {
            JOptionPane.showMessageDialog(this, "BERHASIL CLAIM TICKET.\n" + "Acara: " + nama_acara + "\nKategori: " + kategori + "\nTanggal Acara: " + tanggal_acara + "\nLokasi: " + lokasi + "\n\nTanggal Claim Ticket: " + LocalDate.now().toString());
            DaftarAcaraPending form = new DaftarAcaraPending();
            form.setVisible(true);
            this.setVisible(false);
            form.usn = usn;
            form.isiData();
            form.tampil();
            form.getMessage();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaimTicketAcara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton jButtonClaim;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelKat;
    private javax.swing.JLabel labelLokasi;
    private javax.swing.JLabel labelNamaAcr;
    private javax.swing.JLabel labelNamaAkun;
    private javax.swing.JLabel labelTgl;
    // End of variables declaration//GEN-END:variables
}
