/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiketwebservice.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DetailPesanParkir extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form DetailPesanParkir
     */
    public String usn;
    public String namaMall;
    public String lantai;
    public String tanggal;
    public String slotNumber;
    Socket s;
    Thread t;
    BufferedReader in;
    DataOutputStream out;

    public DetailPesanParkir() {
        try {
            initComponents();

            //TCP
            s = new Socket("localhost", 6002);
            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }
        } catch (IOException ex) {
            System.out.println("Error di constructor = " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelTgl = new javax.swing.JLabel();
        jLabelNamaAkun = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelLantai = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jButtonPesan = new javax.swing.JButton();
        jLabelSlot = new javax.swing.JLabel();
        buttonBack1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Nama Pemesan");
        jPanelMain.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("Tanggal Parkir");
        jPanelMain.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText(":");
        jPanelMain.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 19, -1));

        jLabelTgl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTgl.setText("tanggal_parkir");
        jPanelMain.add(jLabelTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        jLabelNamaAkun.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNamaAkun.setText("namaPemesan");
        jPanelMain.add(jLabelNamaAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText(":");
        jPanelMain.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 19, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setText(":");
        jPanelMain.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 19, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText(":");
        jPanelMain.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 19, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Lantai");
        jPanelMain.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Nama Tempat");
        jPanelMain.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabelLantai.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelLantai.setText("lantai");
        jPanelMain.add(jLabelLantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabelNama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNama.setText("nama_tempat");
        jPanelMain.add(jLabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jButtonPesan.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButtonPesan.setText("Pesan Sekarang");
        jButtonPesan.setToolTipText("");
        jButtonPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesanActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        jLabelSlot.setFont(new java.awt.Font("Verdana", 1, 60)); // NOI18N
        jLabelSlot.setForeground(new java.awt.Color(107, 114, 61));
        jLabelSlot.setText("A1");
        jPanelMain.add(jLabelSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        buttonBack1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        buttonBack1.setText("<");
        buttonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBack1ActionPerformed(evt);
            }
        });
        jPanelMain.add(buttonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/images/bgKonfirmasiPemesananParkir.png"))); // NOI18N
        jPanelMain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesanActionPerformed
        // TODO add your handling code here:
        try {
            // Mendapatkan tanggal hari ini
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal_pembelian = dateFormat.format(new Date());

            // Membuat string chatClient sesuai urutan server
            String chatClient = "Pesan Parkir-n" + slotNumber + "-m" + tanggal_pembelian + "-m" + tanggal + "-m" + lantai + "-m" + usn + "-m" + namaMall;

            System.out.println(chatClient);

            // Mengirim data ke server
            DataOutputStream out = new DataOutputStream(s.getOutputStream());
            out.writeBytes(chatClient + "\n");
            getMessage();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonPesanActionPerformed

    private void buttonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBack1ActionPerformed
        // TODO add your handling code here:
        Parkir form = new Parkir();
        form.setVisible(true);
        this.setVisible(false);
        form.usn = usn;
        form.isiData();
        form.KosongRB();
    }//GEN-LAST:event_buttonBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void run() {
        while (true) {
            try {
                tampil();
            } catch (Exception e) {
                System.out.println("Error in run method: " + e);
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPesanParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPesanParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPesanParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPesanParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailPesanParkir().setVisible(true);
            }
        });
    }

    public void getMessage() throws IOException {
        String chatServer;

        in = new BufferedReader(new InputStreamReader(s.getInputStream()));
        chatServer = in.readLine();
        System.out.println(chatServer);

        String[] arrayDariServer = chatServer.split("-n");
        String status = arrayDariServer[0];

        if (status.equals("Berhasil Reservasi Parkir")) {
            JOptionPane.showMessageDialog(this, "BERHASIL RESERVASI.\n" + "Nama Tempat: " + namaMall + "\nLantai: " + lantai + "\nSlot: " + slotNumber + "\nTanggal: " + tanggal);
            Parkir form = new Parkir();
            form.setVisible(true);
            this.setVisible(false);
            form.tampilDaftarTempat();
            form.usn = usn;
            form.isiData();
            form.KosongRB();
        }
        else if (status.contains("Sudah dipesan")){
            JOptionPane.showMessageDialog(this, "Maaf, slot ini sudah direservasi untuk hari ini.\n", "Error",JOptionPane.ERROR_MESSAGE);
        }
        else if (status.contains("Gagal Reservasi Parkir")){
            JOptionPane.showMessageDialog(this, "GAGAL RESERVASI.\n", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tampil() {
        jLabelNamaAkun.setText(usn);
        jLabelNama.setText(namaMall);
        jLabelLantai.setText(lantai);
        jLabelTgl.setText(tanggal);
        jLabelSlot.setText(slotNumber);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack1;
    private javax.swing.JButton jButtonPesan;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLantai;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNamaAkun;
    private javax.swing.JLabel jLabelSlot;
    private javax.swing.JLabel jLabelTgl;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
