/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiketwebservice.ui;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JRadioButton;
import java.awt.*;
import java.util.*;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author user
 */
public class Parkir extends javax.swing.JFrame implements Runnable {

    Socket s;
    Thread t;
    BufferedReader in;
    DataOutputStream out;
    String usn;
    String namaMall;
    String lantai;
    String tanggal;
    String slotNumber;
    String lokasi;
    private String selectedSlotName;

    /**
     * Creates new form Parkir
     */
    public Parkir() {
        try {
            initComponents();
            //TCP
            s = new Socket("localhost", 6002);
            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }
        } catch (IOException ex) {
            System.out.println("Error di constructor = " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void isiData() {
        txtNama.setText(usn);
    }

    public void KosongRB() {
        for (Component cp : jPanelA.getComponents()) {
            if (cp instanceof JRadioButton) {
                cp.setEnabled(false);
                cp.setForeground(Color.WHITE);
            }

        }
        for (Component cp : jPanelB.getComponents()) {
            if (cp instanceof JRadioButton) {
                cp.setEnabled(false);
                cp.setForeground(Color.WHITE);
            }

        }
        for (Component cp : jPanelC.getComponents()) {
            if (cp instanceof JRadioButton) {
                cp.setEnabled(false);
                cp.setForeground(Color.WHITE);
            }
        }
    }

    public void IsiRB() {
        for (Component cp : jPanelA.getComponents()) {
            if (cp instanceof JRadioButton) {
                cp.setEnabled(true);
                cp.setForeground(Color.WHITE);
            }

        }
        for (Component cp : jPanelB.getComponents()) {
            if (cp instanceof JRadioButton) {
                cp.setEnabled(true);
                cp.setForeground(Color.WHITE);
            }

        }
        for (Component cp : jPanelC.getComponents()) {
            if (cp instanceof JRadioButton) {
                cp.setEnabled(true);
                cp.setForeground(Color.WHITE);
            }

        }
    }

    public void tampilDaftarTempat() {
        try {
            String chatClient;
            chatClient = "Lihat Daftar Tempat";
            DataOutputStream out = new DataOutputStream(s.getOutputStream());
            out.writeBytes(chatClient + "\n");
            System.out.println("Chat Terkirim");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void getMessage() throws IOException {
        System.out.println("mulai masuk get message");
        String chatServer;

        in = new BufferedReader(new InputStreamReader(s.getInputStream()));
        chatServer = in.readLine();

        System.out.println(chatServer);
        String[] arrayDariServer = chatServer.split("-n");

        String status = arrayDariServer[0];

        if (status.equals("Daftar Tempat")) {
            System.out.println("masuk ke mengeset");
            String textLong = arrayDariServer[1];
            String[] arrayDariTextLong = textLong.split("#");

            jComboBoxNamaMall.setModel(new DefaultComboBoxModel<>(arrayDariTextLong));
        } else if (status.equals("Gagal Daftar Tempat")) {
            System.out.println("Tidak ada daftar tempat");
        } else if (status.equals("Daftar")) {
            System.out.println("Balasan Search Button " + arrayDariServer[1]);
            String[] message = arrayDariServer[1].split("-m");
            if (message != null) {
                System.out.println("Array dari server tidak null");
                System.out.println(message[0]);
                for (String s : message) {
                    if (s.contains("A")) {
                        for (Component cp : jPanelA.getComponents()) {
                            JRadioButton rb = (JRadioButton) cp;
                            String aa = "A" + rb.getText();
                            if (aa.equals(s)) {
                                rb.setEnabled(false);
                                rb.setForeground(Color.RED);
                            }
                        }
                    } else if (s.contains("B")) {
                        System.out.println("Masuk B nih");
                        for (Component cp : jPanelB.getComponents()) {
                            JRadioButton rb = (JRadioButton) cp;
                            String aa = "B" + rb.getText();
                            if (aa.equals(s)) {
                                rb.setEnabled(false);
                                rb.setForeground(Color.RED);
                            }
                        }
                    } else if (s.contains("C")) {
                        for (Component cp : jPanelC.getComponents()) {
                            JRadioButton rb = (JRadioButton) cp;
                            String aa = "C" + rb.getText();
                            if (aa.equals(s)) {
                                rb.setEnabled(false);
                                rb.setForeground(Color.RED);
                            }
                        }
                    }
                }
            }
        }
    }

    @Override
    public void run() {
        try {
            getMessage();
            KosongRB();
        } catch (Exception ex) {
            System.out.println("Error run parkir: " + ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxNamaMall = new javax.swing.JComboBox<>();
        jComboBoxLantai = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        jButtonPesanPark1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelA = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jPanelB = new javax.swing.JPanel();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton490 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jRadioButton61 = new javax.swing.JRadioButton();
        jPanelC = new javax.swing.JPanel();
        jRadioButton62 = new javax.swing.JRadioButton();
        jRadioButton63 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jRadioButton66 = new javax.swing.JRadioButton();
        jRadioButton67 = new javax.swing.JRadioButton();
        jRadioButton68 = new javax.swing.JRadioButton();
        jRadioButton69 = new javax.swing.JRadioButton();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton71 = new javax.swing.JRadioButton();
        jRadioButton72 = new javax.swing.JRadioButton();
        jRadioButton73 = new javax.swing.JRadioButton();
        jRadioButton74 = new javax.swing.JRadioButton();
        jRadioButton75 = new javax.swing.JRadioButton();
        jRadioButton76 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabelLokasi = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxNamaMall.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNamaMall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNamaMallActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxNamaMall, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 133, -1));

        jComboBoxLantai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B2", "LG", "G" }));
        jComboBoxLantai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLantaiActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxLantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 133, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setText("Pilih lantai");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        txtNama.setFont(new java.awt.Font("Verdana", 1, 34)); // NOI18N
        txtNama.setText("nama");
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jButtonPesanPark1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButtonPesanPark1.setText("Pesan Tiket");
        jButtonPesanPark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesanPark1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesanPark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 160, 38));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel9.setText("Pilih Tanggal");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 235, 208));
        jLabel1.setText("A");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 235, 208));
        jLabel2.setText("B");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 235, 208));
        jLabel7.setText("C");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, -1));

        jPanelA.setBackground(new java.awt.Color(107, 114, 61));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("2");
        jRadioButton2.setName("A2"); // NOI18N
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("3");
        jRadioButton3.setName("A3"); // NOI18N
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("1");
        jRadioButton1.setName("A1"); // NOI18N
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("7");
        jRadioButton7.setName("A7"); // NOI18N
        jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton7MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("4");
        jRadioButton4.setName("A4"); // NOI18N
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("13");
        jRadioButton13.setName("A13"); // NOI18N
        jRadioButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton13MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("5");
        jRadioButton5.setName("A5"); // NOI18N
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("6");
        jRadioButton6.setName("A6"); // NOI18N
        jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton6MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("8");
        jRadioButton8.setName("A8"); // NOI18N
        jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton8MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("9");
        jRadioButton9.setName("A9"); // NOI18N
        jRadioButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton9MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("11");
        jRadioButton11.setName("A11"); // NOI18N
        jRadioButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton11MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("12");
        jRadioButton12.setName("A12"); // NOI18N
        jRadioButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton12MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("14");
        jRadioButton14.setName("A14"); // NOI18N

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("15");
        jRadioButton15.setName("A15"); // NOI18N
        jRadioButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton15MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("10");
        jRadioButton10.setName("A10"); // NOI18N
        jRadioButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelALayout = new javax.swing.GroupLayout(jPanelA);
        jPanelA.setLayout(jPanelALayout);
        jPanelALayout.setHorizontalGroup(
            jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelALayout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton5))
                    .addGroup(jPanelALayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanelALayout.createSequentialGroup()
                        .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelALayout.createSequentialGroup()
                                .addComponent(jRadioButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton15))
                            .addGroup(jPanelALayout.createSequentialGroup()
                                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton11)
                                    .addComponent(jRadioButton8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton9)
                                    .addComponent(jRadioButton12)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton3))))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelALayout.setVerticalGroup(
            jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(24, 24, 24)
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton10))
                .addGap(18, 18, 18)
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 180, 240));

        jPanelB.setBackground(new java.awt.Color(107, 114, 61));

        buttonGroup1.add(jRadioButton47);
        jRadioButton47.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton47.setText("2");
        jRadioButton47.setName("B2"); // NOI18N
        jRadioButton47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton47MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton48);
        jRadioButton48.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton48.setText("3");
        jRadioButton48.setName("B3"); // NOI18N
        jRadioButton48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton48MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton490);
        jRadioButton490.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton490.setText("1");
        jRadioButton490.setName("B1"); // NOI18N
        jRadioButton490.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton490MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton50);
        jRadioButton50.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton50.setText("7");
        jRadioButton50.setName("B7"); // NOI18N
        jRadioButton50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton50MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton51);
        jRadioButton51.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton51.setText("4");
        jRadioButton51.setName("B4"); // NOI18N
        jRadioButton51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton51MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton52);
        jRadioButton52.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton52.setText("13");
        jRadioButton52.setName("B13"); // NOI18N
        jRadioButton52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton52MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton53);
        jRadioButton53.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton53.setText("5");
        jRadioButton53.setName("B5"); // NOI18N
        jRadioButton53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton53MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton54);
        jRadioButton54.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton54.setText("6");
        jRadioButton54.setName("B6"); // NOI18N
        jRadioButton54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton54MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton55);
        jRadioButton55.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton55.setText("8");
        jRadioButton55.setName("B8"); // NOI18N
        jRadioButton55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton55MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton56);
        jRadioButton56.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton56.setText("9");
        jRadioButton56.setName("B9"); // NOI18N
        jRadioButton56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton56MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton57);
        jRadioButton57.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton57.setText("11");
        jRadioButton57.setName("B11"); // NOI18N
        jRadioButton57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton57MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton58);
        jRadioButton58.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton58.setText("12");
        jRadioButton58.setName("B12"); // NOI18N
        jRadioButton58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton58MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton59);
        jRadioButton59.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton59.setText("14");
        jRadioButton59.setName("B14"); // NOI18N
        jRadioButton59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton59MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton60);
        jRadioButton60.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton60.setText("15");
        jRadioButton60.setName("B15"); // NOI18N
        jRadioButton60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton60MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton61);
        jRadioButton61.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton61.setText("10");
        jRadioButton61.setName("B10"); // NOI18N
        jRadioButton61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton61MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelBLayout = new javax.swing.GroupLayout(jPanelB);
        jPanelB.setLayout(jPanelBLayout);
        jPanelBLayout.setHorizontalGroup(
            jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBLayout.createSequentialGroup()
                        .addComponent(jRadioButton51)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton53))
                    .addGroup(jPanelBLayout.createSequentialGroup()
                        .addComponent(jRadioButton490)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton47))
                    .addGroup(jPanelBLayout.createSequentialGroup()
                        .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton52)
                            .addComponent(jRadioButton61)
                            .addComponent(jRadioButton50, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBLayout.createSequentialGroup()
                                .addComponent(jRadioButton59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton60))
                            .addGroup(jPanelBLayout.createSequentialGroup()
                                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton57)
                                    .addComponent(jRadioButton55))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton56)
                                    .addComponent(jRadioButton58)
                                    .addComponent(jRadioButton54)
                                    .addComponent(jRadioButton48))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBLayout.setVerticalGroup(
            jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton47)
                    .addComponent(jRadioButton48)
                    .addComponent(jRadioButton490))
                .addGap(26, 26, 26)
                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton54))
                .addGap(24, 24, 24)
                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton50)
                    .addComponent(jRadioButton55)
                    .addComponent(jRadioButton56))
                .addGap(18, 18, 18)
                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton57)
                    .addComponent(jRadioButton58)
                    .addComponent(jRadioButton61))
                .addGap(18, 18, 18)
                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton59)
                    .addComponent(jRadioButton60))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 180, 240));

        jPanelC.setBackground(new java.awt.Color(107, 114, 61));

        buttonGroup1.add(jRadioButton62);
        jRadioButton62.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton62.setText("2");
        jRadioButton62.setName("C2"); // NOI18N
        jRadioButton62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton62MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton63);
        jRadioButton63.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton63.setText("3");
        jRadioButton63.setName("C3"); // NOI18N
        jRadioButton63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton63MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton64);
        jRadioButton64.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton64.setText("1");
        jRadioButton64.setName("C1"); // NOI18N
        jRadioButton64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton64MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton65);
        jRadioButton65.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton65.setText("7");
        jRadioButton65.setName("C7"); // NOI18N
        jRadioButton65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton65MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton66);
        jRadioButton66.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton66.setText("4");
        jRadioButton66.setName("C4"); // NOI18N
        jRadioButton66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton66MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton67);
        jRadioButton67.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton67.setText("13");
        jRadioButton67.setName("C13"); // NOI18N
        jRadioButton67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton67MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton68);
        jRadioButton68.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton68.setText("5");
        jRadioButton68.setName("C5"); // NOI18N
        jRadioButton68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton68MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton69);
        jRadioButton69.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton69.setText("6");
        jRadioButton69.setName("C6"); // NOI18N
        jRadioButton69.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton69MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton70);
        jRadioButton70.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton70.setText("8");
        jRadioButton70.setName("C8"); // NOI18N
        jRadioButton70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton70MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton71);
        jRadioButton71.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton71.setText("9");
        jRadioButton71.setName("C9"); // NOI18N
        jRadioButton71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton71MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton72);
        jRadioButton72.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton72.setText("11");
        jRadioButton72.setName("C11"); // NOI18N
        jRadioButton72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton72MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton73);
        jRadioButton73.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton73.setText("12");
        jRadioButton73.setName("C12"); // NOI18N
        jRadioButton73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton73MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton74);
        jRadioButton74.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton74.setText("14");
        jRadioButton74.setName("C14"); // NOI18N
        jRadioButton74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton74MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton75);
        jRadioButton75.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton75.setText("15");
        jRadioButton75.setName("C15"); // NOI18N
        jRadioButton75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton75MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton76);
        jRadioButton76.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton76.setText("10");
        jRadioButton76.setName("C10"); // NOI18N
        jRadioButton76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton76MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCLayout = new javax.swing.GroupLayout(jPanelC);
        jPanelC.setLayout(jPanelCLayout);
        jPanelCLayout.setHorizontalGroup(
            jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCLayout.createSequentialGroup()
                        .addComponent(jRadioButton66)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton68))
                    .addGroup(jPanelCLayout.createSequentialGroup()
                        .addComponent(jRadioButton64)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton62))
                    .addGroup(jPanelCLayout.createSequentialGroup()
                        .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton67)
                            .addComponent(jRadioButton76)
                            .addComponent(jRadioButton65, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCLayout.createSequentialGroup()
                                .addComponent(jRadioButton74)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton75))
                            .addGroup(jPanelCLayout.createSequentialGroup()
                                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton72)
                                    .addComponent(jRadioButton70))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton71)
                                    .addComponent(jRadioButton73)
                                    .addComponent(jRadioButton69)
                                    .addComponent(jRadioButton63))))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCLayout.setVerticalGroup(
            jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton62)
                    .addComponent(jRadioButton63)
                    .addComponent(jRadioButton64))
                .addGap(18, 18, 18)
                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton66)
                    .addComponent(jRadioButton68)
                    .addComponent(jRadioButton69))
                .addGap(24, 24, 24)
                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton65)
                    .addComponent(jRadioButton70)
                    .addComponent(jRadioButton71))
                .addGap(18, 18, 18)
                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton72)
                    .addComponent(jRadioButton73)
                    .addComponent(jRadioButton76))
                .addGap(18, 18, 18)
                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton67)
                    .addComponent(jRadioButton74)
                    .addComponent(jRadioButton75))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 180, 240));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("merah");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setText(":  tidak bisa dipesan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel4.setText("Pilih mall");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 146, -1));
        jPanel1.add(jLabelLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 30, -1, -1));

        buttonBack.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        buttonBack.setText("<");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 19, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/images/bgParkir.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        WelcomePage form = new WelcomePage();
        form.setVisible(true);
        this.setVisible(false);
        form.usn = usn;
        form.isiData();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        // TODO add your handling code here:
        try {
            String mall = "", lantai = "", tanggal = "";
            this.IsiRB();
            if (jComboBoxNamaMall.getSelectedIndex() != -1 || jComboBoxLantai.getSelectedIndex() != -1) {
                mall = jComboBoxNamaMall.getSelectedItem().toString();
                lantai = jComboBoxLantai.getSelectedItem().toString();
                Date selectedDate = jDateChooser2.getDate();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                tanggal = dateFormat.format(selectedDate).toString();
            }
            String chatClient;
            chatClient = "Lihat Reservasi-n" + mall + "-m" + lantai + "-m" + tanggal;
            DataOutputStream out = new DataOutputStream(s.getOutputStream());
            System.out.println(chatClient);
            out.writeBytes(chatClient + "\n");
            this.getMessage();

        } catch (Exception ex) {
            System.out.println("Error di buttonSearch: belum memilih tanggal");
        }
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void jRadioButton76MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton76MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton76MouseClicked

    private void jRadioButton75MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton75MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton75MouseClicked

    private void jRadioButton74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton74MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton74MouseClicked

    private void jRadioButton73MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton73MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton73MouseClicked

    private void jRadioButton72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton72MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton72MouseClicked

    private void jRadioButton71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton71MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton71MouseClicked

    private void jRadioButton70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton70MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton70MouseClicked

    private void jRadioButton69MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton69MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton69MouseClicked

    private void jRadioButton68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton68MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton68MouseClicked

    private void jRadioButton67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton67MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton67MouseClicked

    private void jRadioButton66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton66MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton66MouseClicked

    private void jRadioButton65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton65MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton65MouseClicked

    private void jRadioButton64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton64MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton64MouseClicked

    private void jRadioButton63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton63MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton63MouseClicked

    private void jRadioButton62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton62MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton62MouseClicked

    private void jRadioButton61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton61MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton61MouseClicked

    private void jRadioButton60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton60MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton60MouseClicked

    private void jRadioButton59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton59MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton59MouseClicked

    private void jRadioButton58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton58MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton58MouseClicked

    private void jRadioButton57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton57MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton57MouseClicked

    private void jRadioButton56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton56MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton56MouseClicked

    private void jRadioButton55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton55MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton55MouseClicked

    private void jRadioButton54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton54MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton54MouseClicked

    private void jRadioButton53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton53MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton53MouseClicked

    private void jRadioButton52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton52MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton52MouseClicked

    private void jRadioButton51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton51MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton51MouseClicked

    private void jRadioButton50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton50MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton50MouseClicked

    private void jRadioButton490MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton490MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton490MouseClicked

    private void jRadioButton48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton48MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton48MouseClicked

    private void jRadioButton47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton47MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton47MouseClicked

    private void jRadioButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton10MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton10MouseClicked

    private void jRadioButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton15MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton15MouseClicked

    private void jRadioButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton12MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton12MouseClicked

    private void jRadioButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton11MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton11MouseClicked

    private void jRadioButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton9MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton9MouseClicked

    private void jRadioButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton8MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton8MouseClicked

    private void jRadioButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton6MouseClicked

    private void jRadioButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton5MouseClicked

    private void jRadioButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton13MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton13MouseClicked

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton4MouseClicked

    private void jRadioButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton7MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        mouseClicked(evt);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jButtonPesanPark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesanPark1ActionPerformed
        // TODO add your handling code here:\
        namaMall = jComboBoxNamaMall.getSelectedItem().toString();
        //String lokasi = "Lokasi Mall"; // Ambil lokasi mall dari sumber yang sesuai
        lantai = jComboBoxLantai.getSelectedItem().toString();
        Date selectedDate = jDateChooser2.getDate();
        System.out.println(selectedDate);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        tanggal = dateFormat.format(selectedDate).toString();
        slotNumber = selectedSlotName;

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate tanggalHariIni = LocalDate.now();
        LocalDate parkirDate = LocalDate.parse(tanggal, formatter);

        if (parkirDate.isAfter(tanggalHariIni) || parkirDate.equals(tanggalHariIni)) {
            DetailPesanParkir form = new DetailPesanParkir();
            form.namaMall = namaMall;
            form.lantai = lantai;
            form.tanggal = tanggal;
            form.slotNumber = slotNumber;
            form.usn = usn;
            form.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Maaf, mohon pilih tanggal parkir minimal hari ini", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPesanPark1ActionPerformed

    private void jComboBoxLantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLantaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLantaiActionPerformed

    private void jComboBoxNamaMallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNamaMallActionPerformed
        // TODO add your handling code here:
        String tempatDipilih = (String) jComboBoxNamaMall.getSelectedItem();
    }//GEN-LAST:event_jComboBoxNamaMallActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {
        javax.swing.JRadioButton s = (javax.swing.JRadioButton) evt.getSource();
        if (s.isSelected()) {
            String name = s.getName();
            selectedSlotName = name;
            System.out.println(name);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonPesanPark1;
    private javax.swing.JComboBox<String> jComboBoxLantai;
    private javax.swing.JComboBox<String> jComboBoxNamaMall;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLokasi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelA;
    private javax.swing.JPanel jPanelB;
    private javax.swing.JPanel jPanelC;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton490;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton61;
    private javax.swing.JRadioButton jRadioButton62;
    private javax.swing.JRadioButton jRadioButton63;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton66;
    private javax.swing.JRadioButton jRadioButton67;
    private javax.swing.JRadioButton jRadioButton68;
    private javax.swing.JRadioButton jRadioButton69;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JRadioButton jRadioButton71;
    private javax.swing.JRadioButton jRadioButton72;
    private javax.swing.JRadioButton jRadioButton73;
    private javax.swing.JRadioButton jRadioButton74;
    private javax.swing.JRadioButton jRadioButton75;
    private javax.swing.JRadioButton jRadioButton76;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JLabel txtNama;
    // End of variables declaration//GEN-END:variables
}
