/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiketwebservice.ui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class WelcomePage extends javax.swing.JFrame {
    public String usn;
    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNama = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jButtonClaimAcara = new javax.swing.JButton();
        jButtonTiketAcara = new javax.swing.JButton();
        jButtonTiketParkir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setFont(new java.awt.Font("Verdana", 1, 34)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setText("name");
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 130, 60));

        jButtonLogout.setText("LOG OUT");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));

        jButtonClaimAcara.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButtonClaimAcara.setText("Claim Ticket Acara");
        jButtonClaimAcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClaimAcaraActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClaimAcara, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jButtonTiketAcara.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButtonTiketAcara.setText("Lihat Acara");
        jButtonTiketAcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiketAcaraActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTiketAcara, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jButtonTiketParkir.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButtonTiketParkir.setText("Lihat Parkir");
        jButtonTiketParkir.setToolTipText("");
        jButtonTiketParkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiketParkirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTiketParkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/images/bgWelcome.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTiketParkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiketParkirActionPerformed
        // TODO add your handling code here:
        Parkir form = new Parkir();
        form.setVisible(true);
        this.setVisible(false);
        form.tampilDaftarTempat();
        form.usn = usn;
        form.isiData();
        form.KosongRB();
    }//GEN-LAST:event_jButtonTiketParkirActionPerformed

    private void jButtonTiketAcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiketAcaraActionPerformed
        // TODO add your handling code here:
        Acara form = new Acara();
        form.setVisible(true);
        this.setVisible(false);
        form.tampil();
        form.usn = usn;
        form.isiData();
    }//GEN-LAST:event_jButtonTiketAcaraActionPerformed

    private void jButtonClaimAcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClaimAcaraActionPerformed
        try {
            // TODO add your handling code here:
            DaftarAcaraPending form = new DaftarAcaraPending();
            form.setVisible(true);
            this.setVisible(false);
            form.usn = usn;
            form.isiData();
            form.tampil();
            form.getMessage();
        } catch (IOException ex) {
            Logger.getLogger(WelcomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonClaimAcaraActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        Login form = new Login();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }
    
     public void isiData() {
        txtNama.setText(usn);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClaimAcara;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonTiketAcara;
    private javax.swing.JButton jButtonTiketParkir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtNama;
    // End of variables declaration//GEN-END:variables
}
